#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Poly Fit - 정기적 후보자 데이터 자동 갱신 파이프라인
GitHub Actions에서 주간 수행
"""

import os
import json
import datetime
from pathlib import Path

# 현재 작업 디렉토리
SCRIPT_DIR = Path(__file__).parent.parent
DATA_JS_PATH = SCRIPT_DIR / "data.js"

def log(message):
    """로그 출력"""
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] {message}")

def fetch_news_snippets(candidate_name):
    """
    후보자의 최근 발언/뉴스 수집 (가상 구현)
    실제로는 웹스크래핑이나 API 사용
    """
    log(f"'{candidate_name}' 후보자의 최근 발언 수집 중...")
    
    # 가상의 최근 뉴스 데이터
    news_db = {
        "조규일": "경제 활성화와 일자리 창출을 통한 지역 발전",
        "류재수": "주민 복지 확대와 취약계층 지원",
        "갈상돈": "청년 정책과 스타트업 지원 강화"
    }
    return news_db.get(candidate_name, "발언 수집 대기 중")

def update_pledges(candidate_data):
    """
    후보자 공약 정보 업데이트
    (실제로는 LLM API 사용)
    """
    name = candidate_data.get("name", "")
    news = fetch_news_snippets(name)
    
    # 기존 공약 유지 (API 연동 시 갱신)
    return candidate_data

def generate_data_js():
    """
    data.js 파일 자동 생성
    """
    candidates = [
        {
            "id": 1,
            "name": "조규일",
            "party": "국민의힘",
            "bio": "현) 진주시장",
            "desc": "경제 활성화와 남부내륙철도 역세권 개발 강조",
            "pledges": {
                "welfare": "취업 연계형 맞춤형 복지 확대",
                "education": "명품 학군 조성",
                "transport": "남부내륙철도 조기 개통",
                "culture": "문화예술 인프라 확충",
                "housing": "재개발/재건축 규제 완화",
                "environment": "친환경 도시 정비"
            }
        },
        {
            "id": 2,
            "name": "류재수",
            "party": "진보당",
            "bio": "전) 진주시의원",
            "desc": "주민 중심의 따뜻한 도시 건설",
            "pledges": {
                "welfare": "보편적 무상 돌봄 확대",
                "education": "공교육 정상화",
                "transport": "대중교통 무상화",
                "culture": "생활문화센터 강화",
                "housing": "공공임대주택 확대",
                "environment": "탄소 제로 도시"
            }
        },
        {
            "id": 3,
            "name": "갈상돈",
            "party": "더불어민주당",
            "bio": "지역 경제 전문가",
            "desc": "청년과 소상공인을 위한 정책 강화",
            "pledges": {
                "welfare": "청년 기본소득",
                "education": "지역 교육 혁신",
                "transport": "스마트 교통 시스템",
                "culture": "지역 축제 활성화",
                "housing": "청년 주택 공급",
                "environment": "생태계 보전"
            }
        }
    ]
    
    # 각 후보자 데이터 업데이트
    for candidate in candidates:
        update_pledges(candidate)
    
    return candidates

def write_data_js_file(candidates):
    """
    최종 data.js 파일 작성
    """
    log("data.js 파일 생성 중...")
    
    js_content = "// Auto-generated by pipeline\n"
    js_content += "export const candidates = " + json.dumps(candidates, ensure_ascii=False, indent=2) + ";\n"
    
    try:
        with open(DATA_JS_PATH, 'w', encoding='utf-8') as f:
            f.write(js_content)
        log(f"✅ data.js 파일 생성 완료: {DATA_JS_PATH}")
        return True
    except Exception as e:
        log(f"❌ 파일 작성 실패: {e}")
        return False

def main():
    """메인 파이프라인 실행"""
    log("=" * 50)
    log("🔄 Poly Fit 데이터 자동 갱신 파이프라인 시작")
    log("=" * 50)
    
    # 1. 후보자 데이터 생성
    candidates = generate_data_js()
    
    # 2. data.js 파일 작성
    success = write_data_js_file(candidates)
    
    if success:
        log("=" * 50)
        log("✨ 파이프라인 완료!")
        log("=" * 50)
        return 0
    else:
        log("파이프라인 실패")
        return 1

if __name__ == "__main__":
    exit(main())
